# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2039882d1d8144c9ed4f18d4719e653e8a8bddd84172a30420b8d9ab95b143d54ec860522268f9dc87a4e66d0b2496443e5ca1f58d3bdf4fb86654af312a79e0

test:
  secret_key_base: 2aabbf2a6e08ac35ede1dee46d998e503f05885bf3afe2252bfe771c19a1c24a066ee07a64cb0ebd4978640557b0cd8b478e28c89780bf9bff8122b586fa6045

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 249da1b544fdb9ba772a3e8b2385d95b6099ed6772b2b09dd262f6807a410edca04f7ec93ae32325d1649de698a38b4b7daa32ed3289b6d1c651a64f354d95d6
